Search for iconv in configure script
macOS requires -liconv in the LDFLAGS to link correctly. So add a
search macro to the configure script to prevent following error:

g++  -g -O2   -o rkdeveloptool main.o crc.o RKBoot.o RKComm.o RKDevice.o
RKImage.o RKLog.o RKScan.o -L/usr/local/Cellar/libusb/1.0.21/lib -lusb-1.0
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      StringToWideString(char*, wchar_t*&) in main.o
      WideStringToString(wchar_t*, char*&) in main.o
  "_iconv_close", referenced from:
      StringToWideString(char*, wchar_t*&) in main.o
      WideStringToString(wchar_t*, char*&) in main.o
  "_iconv_open", referenced from:
      StringToWideString(char*, wchar_t*&) in main.o
      WideStringToString(wchar_t*, char*&) in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [rkdeveloptool] Error 1